### ISSUE TITLE
iamRoleConfig not working

### ISSUE THREAD

**Issue by ahansson89** [spotinst/serverless-spotinst-functions#23]
Here is my example function

```
functions:
  example:
    handler: example.main
    runtime: nodejs8.3
    memory: 128
    timeout: 30
    access: public
    iamRoleConfig:
      roleId: sfr-12345ffs
    endpoint:
      path: /example
      method: get
```

When deploying the function the iamRoleConfig passed on to the function.
In the web console, this works
